# Generated by Django 2.0.7 on 2020-08-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votestatus',
            old_name='name',
            new_name='user',
        ),
    ]
